### ISSUE TITLE
How to retrieve more than 1000 records

### ISSUE THREAD

**Issue by wreyford** [d-markey/azure_cosmosdb#3]
I need to return a months telemetry data at a time.
Currently when I query a container it only returns 1000 records of 30000 records.

How can i get the continuation token, and then re-query with it to get the next 1000 records, until continuation token is empty, thus no more records.

I see it is in header: x-ms-continuation
Is see in lib/src there is a query and pagination class.
However pagination wont solve my problem.

Is there a way to get the header x-ms-continuation from the result when using container.query<telemetry>(Query('select * from telem', 
maxCount: -1));
Any advice will be appreciated. Thx

**Comment by d-markey** [comment]
Hello,

CosmosDb has a limit built-in to 1000 according to https://learn.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api#pagination-of-query-results.

It's up to you to replay the query until the continuation token is empty. You can find an example in the "Query multiple documents with paging" test case (cf. https://github.com/d-markey/azure_cosmosdb/blob/main/test/test_suites/document_queries.dart). To get the full list of items, use something like `while (query.continuation.isNotEmpty)` after the first call.

**Comment by wreyford** [comment]
Hello, d-markey,
Thank you so much👋👋

I actually checked your tests for clues, but must missed the `query.continuation.isempty` property.
I also note `query.first.id`. These are tucked away  in your tests and very useful. 

Yes I am aware of the 1000 limit, and thus i needed a way to set paginate to 1000, and step through. I had macCount set to -1, and thus ran into the 1000 records limit.

**Comment by wreyford** [comment]
Excellent package, appreciate your well written package.

**Comment by d-markey** [comment]
Thanks! Glad you find it useful
