### ISSUE TITLE
BadResponseException: Expected a value of type 'int', but got one of type 'Null'

### ISSUE THREAD

**Issue by wreyford** [d-markey/azure_cosmosdb#4]

**Comment by wreyford** [comment]
Sorry, I deleted as was my error in parsing in my fromJson class, and debugging took me to your error handling, and I was on the wrong track!

**Comment by d-markey** [comment]
no problem :)

**Comment by carlkenne** [comment]
I'm just trying this out today and I got the exact same issue when running database.containers.openOrCreate, haven't touched my fromJson yet. @wreyford could you explain how you managed to track this issue down?

**Comment by carlkenne** [comment]
I'm started testing this today and ran in to the exact same error message. I get it very early on when calling database.containers.openOrCreate (internally it's failing in context.getBuilder()), haven't reached the fromJson code yet. @wreyford, how did you manage to track your issue down?
