### ISSUE TITLE
Not an Issue, just need some pointers on passing of params in queries.

### ISSUE THREAD

**Issue by wreyford** [d-markey/azure_cosmosdb#5]
I am attempting a query with params, but failing:

The following works:
```
final allWeightsQuery = Query(
    'SELECT '
    'w.id, '
    'w.ph_weight_device_mac_date, '
    'FROM w '
    'WHERE w.ph_weight_device_mac_date IN (@dm)',
        params: {'@dm': '73DFA1D6CD50-2023-08-15'}, 
        maxCount: -1,
     );
```
but I would like to use **WHERE x IN (value1, value2, value3...)**

How do I construct the param:
I tried:
```
 'WHERE w.ph_weight_device_mac_date IN (@dm)',
      params: {'@dm': '73DFA1D6CD50-2023-08-15, 73DFA1D6C3F0-2023-08-26'},
``` 
but this fails to return any data.
So, how do I include a param for IN LIST of values.?

**Comment by wreyford** [comment]
I also tried:
```
var item = ['73DFA1D6CD50-2023-08-15','73DFA1D6C3F0-2023-08-26'];
...
'WHERE w.ph_weight_device_mac_date IN (@dm)',
      maxCount: -1,
      params:  {'@dm': item},
```
Also fails...

**Comment by wreyford** [comment]
```
'FROM w '
    'WHERE w.ph_weight_device_mac_date IN (@dm,@dm2) ',
      params:  {'@dm': '73DFA1D6CD50-2023-08-15', '@dm2': '73DFA1D6C3F0-2023-08-26'},
```

Works ...but then I am limited and have to know at compile time the number of parameters to include. Is there another way?

**Comment by d-markey** [comment]
I think you're looking for `ARRAY_CONTAINS`, see example here:

https://github.com/d-markey/azure_cosmosdb/blob/d18a8e4ab7dd302d1b45f5c6faa8e96e5ca50b51/example/batch.dart#L71-L75

**Comment by wreyford** [comment]
Brilliant! Thx
