### ISSUE TITLE
A question: How do I Access the user Claims in application code

### ISSUE THREAD

**Issue by wreyford** [d-markey/azure_cosmosdb#6]
I have a Flutter web app running on azure, and can successfully use you plugin to retrieve data from Cosmos DB.
According to Microsoft: [https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities#access-user-claims-in-app-code](https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities#access-user-claims-in-app-code)

I see from your src code that you get an auth token back.

Is there a way that you can recommend or point me to to obtain the authenticated users Username or Email, so I can branch the codes functionality based on user signed in. I use Microsoft's built in Authorization to manage the logins seamlessly to the Web App.
I'm referring to the below... injected into the returned headers (Auth Token)  that you manage.

> <html>
> <body>
> <p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">For all language frameworks, App Service makes the claims in the incoming token (whether from an authenticated end user or a client application) available to your code by injecting them into the request headers. External requests aren't allowed to set these headers, so they're present only if set by App Service. Some example headers include:</p><div class="has-inner-focus" style="box-sizing: inherit; outline-color: inherit; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
> 
> Header | Description
> -- | --
> X-MS-CLIENT-PRINCIPAL | A Base64 encoded JSON representation of available claims. For more information, see Decoding the client principal header.
> X-MS-CLIENT-PRINCIPAL-ID | An identifier for the caller set by the identity provider.
> X-MS-CLIENT-PRINCIPAL-NAME | A human-readable name for the caller set by the identity provider, e.g. Email Address, User Principal Name.
> X-MS-CLIENT-PRINCIPAL-IDP | The name of the identity provider used by App Service Authentication.
> 
> </div><p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Provider tokens are also exposed through similar headers. For example, the Microsoft Identity Provider also sets<span> </span><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">X-MS-TOKEN-AAD-ACCESS-TOKEN</code><span> </span>and<span> </span><code style="box-sizing: inherit; outline-color: inherit; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; direction: ltr; background-color: var(--theme-inline-code); overflow-wrap: break-word; border-radius: 3px; padding: 0.1em 0.2em;">X-MS-TOKEN-AAD-ID-TOKEN</code><span> </span>as appropriate.</p>
> </body>
> </html>For all language frameworks, App Service makes the claims in the incoming token (whether from an authenticated end user or a client application) available to your code by injecting them into the request headers. External requests aren't allowed to set these headers, so they're present only if set by App Service. Some example headers include:
> 
> Header	Description
> X-MS-CLIENT-PRINCIPAL	A Base64 encoded JSON representation of available claims. For more information, see [Decoding the client principal header](https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities#decoding-the-client-principal-header).
> X-MS-CLIENT-PRINCIPAL-ID	An identifier for the caller set by the identity provider.
> X-MS-CLIENT-PRINCIPAL-NAME	A human-readable name for the caller set by the identity provider, e.g. Email Address, User Principal Name.
> X-MS-CLIENT-PRINCIPAL-IDP	The name of the identity provider used by App Service Authentication.
> Provider tokens are also exposed through similar headers. For example, the Microsoft Identity Provider also sets X-MS-TOKEN-AAD-ACCESS-TOKEN and X-MS-TOKEN-AAD-ID-TOKEN as appropriate.

I'm hope that you understand what I'm trying to achieve, and that you will be able to give me advice or pointer to code?
Thx

**Comment by wreyford** [comment]
Hello, Do you expose the httpHeaders , 
```
if (traceHeaders) {
      for (var h in request.headers.entries) {
        log('[$ts] --> ${h.key} = ${h.value}');
      }
    }
```

that Azure injects for Authorized Azure WebApp, so that I can extract the X-MS-CLIENT-PRINCIPAL, and decode it, or simply the Human Readable X-MS-CLIENT-PRINCIPAL-NAME, when  making the call to CosmosDBServer as an entry point to my WebApp.

This way I can present the correct WebApp configuration based on the User that seamlessly Signed in with Microsoft AD.
This is my last hurdle.

I looked at your test cases, and on the local debugger I can see the following log, but how to achieve for production. Also the specific header is not locally available on the emulator. DebugHttpClient is not meant for production code..

> [log] [2023-09-20T05:56:13.038Z] <-- COSMOS DB Status = 200 
> [log] [2023-09-20T05:56:13.038Z] <-- access-control-allow-credentials = true
> [log] [2023-09-20T05:56:13.038Z] <-- access-control-allow-origin = http://localhost:1708
> [log] [2023-09-20T05:56:13.038Z] <-- cache-control = no-store, no-cache
> [log] [2023-09-20T05:56:13.038Z] <-- content-location = https://localhost:8081/dbs/loadassist-packhouse
> [log] [2023-09-20T05:56:13.038Z] <-- content-type = application/json
> [log] [2023-09-20T05:56:13.038Z] <-- etag = "00000000-0000-0000-d8cd-7cc1d3e401d9"
> [log] [2023-09-20T05:56:13.038Z] <-- lsn = 49
> [log] [2023-09-20T05:56:13.038Z] <-- pragma = no-cache
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-activity-id = 2f5354d1-2b86-439d-abad-ffe2ded165ce
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-cosmos-item-llsn = 4
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-cosmos-llsn = 49
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-cosmos-quorum-acked-llsn = 49
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-current-replica-set-size = 1
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-current-write-quorum = 1
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-gatewayversion = version=2.14.0
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-global-committed-lsn = -1
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-item-lsn = 4
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-last-state-change-utc = Wed, 20 Sep 2023 05:42:54.458 GMT
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-number-of-read-regions = 0
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-quorum-acked-lsn = 49
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-request-charge = 2
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-request-duration-ms = 0.243
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-resource-quota = databases=1000;
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-resource-usage = databases=1;
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-schemaversion = 1.15
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-serviceversion = version=2.14.0.0
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-session-token = 0:-1#49
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-transport-request-id = 63
> [log] [2023-09-20T05:56:13.038Z] <-- x-ms-xp-role = 0
> [log] [2023-09-20T05:56:13.038Z] <-- COSMOS DB 200 Paylo…s":"colls\/","_users":"users\/","_ts":1693130505}

**Comment by d-markey** [comment]
Hello,

Regarding the auth and identity management, I'm afraid I can't help you.

For the other questions regarding headers, I understand that you would like to enrich/inspect requests sent to/by Cosmos DB, eg. adding additional headers that you've received from a previous call to another Azure service.

If that's the case, then you can implement your own `HttpClient` and override the `send()` method to add your additional headers. This client should be passed to the `CosmosDbServer` so that requests hit your code before they're sent to Cosmos DB. The approach is similar to that of `DebugHttpClient`.

Something like:

```dart
import 'package:http/http.dart' as http;

class CustomHttpClient extends http.BaseClient {
  CustomHttpClient(this._customHeaders) {
    _http = http.Client();
  }

  final Map<String, String> _customHeaders;

  late final http.Client _http;

  @override
  void close() => _http.close();

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    request.headers.addAll(_customHeaders);
    return _http.send(request);
  }
}
```

You'll need to initialize your custom client with proper headers before creating the `CosmosDbServer` instance:

```dart
  final myHttpClient = CustomHttpClient({
    'X-MY-HEADER': 'appropriate data',
  }),

  final server = CosmosDbServer(
    cosmosDbEndpoint,
    key,
    httpClient: myHttpClient,
  );
```

Similarly, if you'd like to extract information from the Cosmos DB response, you can further adapt the custom code to await `_http.send(request)` and get hold of the response to inspect its headers before returning it to the original caller.

**Comment by wreyford** [comment]
Thank you for your very complete response.
