### ISSUE TITLE
If container throughput not set on create , then defaults to CosmosDbThroughput.minimum

### ISSUE THREAD

**Issue by wreyford** [d-markey/azure_cosmosdb#7]
I have a database  with a fixed throughput of 1000 RU/s

I wish to add containers as in the Azure portal, where you just don't tick the checkbox for Provisioning dedicated throughput for the container.

This way all containers in the database share the throughput provisioned for the Database.

If I create the container as follows:
```
final deviceCollection = await database.containers.openOrCreate(
      'device',
      partitionKey: partitionKey,
      throughput: CosmosDbThroughput.autoScale(1000),
      indexingPolicy: indexingPolicy,
    );
```
it provisions 1000RU/s just for that container, thus exceding my 1000 RU/s.

If I set to minimun:
` throughput: CosmosDbThroughput.minimum,`

it obviously sets it to a minimum of 400 RU's

If I leave off the throughput parameter, then it also defaults to 400RU's

How do I NOT provision dedicated throughput for this container? as in the image below:

![provisioned](https://github.com/d-markey/azure_cosmosdb/assets/50998190/0d796ada-a93b-4bb1-8760-e71a42de982a)

**Comment by d-markey** [comment]
Indeed the code uses a default value for throughput when you don't provide one. I'll try and remove it so it inherits from the parent database throughput, I'll keep you posted.

**Comment by djkingCanada** [comment]
I was also looking at this code yesterday as my instance is serverless and thus the solution was to comment out that header.  Obviously not general fix.  If you'd like I can do a pr with an attempt at a more general fix.

**Comment by d-markey** [comment]
Thanks for your contribution, I've added a test case and prepared `pubspec.yaml` before official release.

**Comment by d-markey** [comment]
Version 2.2.0 published! Thanks for your help.

**Comment by wreyford** [comment]
Thx a lot. I had time to test today, and it solves the problem. Much appreciated.
